### ISSUE TITLE
Timeouterror: result expired

### ISSUE THREAD

**Issue by vishalGoundar** [pyscripter/pyscripter#1015] opened 2020-09-01 22:51 UTC
TimeoutError: result expired.

Exception class: EPyWindowsError
Exception message: TimeoutError: result expired.
Exception address: 00000000009A8461
------------------------------------------------------------------------------
PyScripter version : 3.6.3.0 x64
Python DLL : python38.dll
Python Engine : peRemoteTk
------------------------------------------------------------------------------
Stack list, generated 2/09/2020 10:35:35 AM
[0000000000BA2F34]{PyScripter.exe} JclDebug.TJclStackInfoList.Create
[0000000000BA2C78]{PyScripter.exe} JclDebug.JclCreateStackList
[0000000000BA2BF6]{PyScripter.exe} JclDebug.DoExceptionStackTrace
[0000000000BA3D02]{PyScripter.exe} JclDebug.DoExceptNotify
[0000000000B93385]{PyScripter.exe} JclHookExcept.TNotifierItem.DoNotify
[0000000000B935CB]{PyScripter.exe} JclHookExcept.DoExceptNotify
[0000000000B9371D]{PyScripter.exe} JclHookExcept.HookedRaiseException
[000000000040FC83]{PyScripter.exe} System.@RaiseAtExcept (Line 21635, "System.pas" + 32)
[000000000040FCA1]{PyScripter.exe} System.@RaiseExcept (Line 21724, "System.pas" + 2)
[00000000009A8461]{PyScripter.exe} PythonEngine.TPythonEngine.RaiseError (Line 5536, "PythonEngine.pas" + 22)
[00000000009AC4D8]{PyScripter.exe} PythonEngine.TPythonEngine.CheckError (Line 6558, "PythonEngine.pas" + 15)
[0000000000A9D261]{PyScripter.exe} VarPyth.TPythonVariantType.SetProperty (Line 1908, "VarPyth.pas" + 8)
[0000000000A9AB3F]{PyScripter.exe} VarPyth.PatchedDispInvoke (Line 1050, "VarPyth.pas" + 57)
[0000000000A9AF55]{PyScripter.exe} VarPyth.TPythonVariantType.DispInvoke (Line 1112, "VarPyth.pas" + 18)
[000000000045120F]{PyScripter.exe} System.Variants.DispInvokeCore (Line 947, "System.Variants.pas" + 23)
[00000000004512C1]{PyScripter.exe} System.Variants.@DispInvoke (Line 989, "System.Variants.pas" + 11)
[0000000000D94E5D]{PyScripter.exe} cPyRemoteDebugger.TPyRemoteInterpreter.RestoreCommandLine (Line 850, "cPyRemoteDebugger.pas" + 2)
[0000000000D954D6]{PyScripter.exe} cPyRemoteDebugger.TPyRemoteInterpreter.Run$ActRec.$0$Body (Line 953, "cPyRemoteDebugger.pas" + 42)
[0000000000B81F52]{PyScripter.exe} uCommonFunctions.TTimer.RunAction (Line 2224, "uCommonFunctions.pas" + 2)
[0000000000640872]{PyScripter.exe} Vcl.ExtCtrls.TTimer.Timer (Line 3125, "Vcl.ExtCtrls.pas" + 2)
[000000000064069A]{PyScripter.exe} Vcl.ExtCtrls.TTimer.WndProc (Line 3082, "Vcl.ExtCtrls.pas" + 4)
[0000000000515636]{PyScripter.exe} System.Classes.StdWndProc (Line 17974, "System.Classes.pas" + 9)
[00007FF9A9E4E338]{USER32.dll  } Unknown function at CallWindowProcW
[00007FF9A9E4DD79]{USER32.dll  } Unknown function at DispatchMessageW
[00000000006A8433]{PyScripter.exe} Vcl.Forms.TApplication.ProcessMessage (Line 10747, "Vcl.Forms.pas" + 23)
[00000000006A84A8]{PyScripter.exe} Vcl.Forms.TApplication.HandleMessage (Line 10777, "Vcl.Forms.pas" + 1)
[00000000006A88F6]{PyScripter.exe} Vcl.Forms.TApplication.Run (Line 10915, "Vcl.Forms.pas" + 26)
[0000000000F53EBB]{PyScripter.exe} PyScripter.PyScripter (Line 149, "" + 20)
[00007FF9ABCE6FD4]{KERNEL32.DLL} BaseThreadInitThunk
[00007FF9ABE1CEC1]{ntdll.dll   } RtlUserThreadStart
------------------------------------------------------------------------------
System   : Windows 10 Professional, Version: 10.0, Build: 4A61, ""
Processor: Intel, Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz, 2590 MHz MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 64 bits DEP
Memory: 8067; free 3653
Display  : 1366x768 pixels, 32 bpp
------------------------------------------------------------------------------
List of loaded modules:
[0000000000400000] C:\Program Files\PyScripter\PyScripter.exe
           3.6.3.0 - 3.6.3.0
           PyScripter Python IDE
[00007FF9763D0000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\unicodedata.pyd
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF976860000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\libcrypto-1_1.dll
           1.1.1.7 - 1.1.1g
           OpenSSL library
[00007FF976BB0000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\libssl-1_1.dll
           1.1.1.7 - 1.1.1g
           OpenSSL library
[00007FF976C60000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\_ssl.pyd
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF976D10000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\_lzma.pyd
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF976D40000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\_bz2.pyd
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF976D60000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\python38.dll
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF977240000] C:\Windows\System32\PlayToDevice.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           PLAYTODEVICE DLL
[00007FF9772B0000] C:\Windows\System32\dlnashext.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           DLNA Namespace DLL
[00007FF983710000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\_asyncio.pyd
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF986050000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\_queue.pyd
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF989E90000] C:\Windows\System32\EhStorShell.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Enhanced Storage Shell Extension DLL
[00007FF98C3D0000] C:\Windows\System32\EhStorAPI.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Enhanced Storage API
[00007FF98EF80000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\_socket.pyd
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF98F270000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\_overlapped.pyd
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF992640000] C:\WINDOWS\system32\wpdshext.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Portable Devices Shell Extension
[00007FF994170000] C:\WINDOWS\System32\dbghelp.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Image Helper
[00007FF996370000] C:\WINDOWS\SYSTEM32\netapi32.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Net Win32 API DLL
[00007FF996B00000] C:\WINDOWS\SYSTEM32\oleacc.dll
           7.2.19041.1 - 7.2.19041.1 (WinBuild.160101.0800)
           Active Accessibility Core Component
[00007FF9972C0000] C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.450_none_fae7a009761b0b44\gdiplus.dll
           6.2.19041.450 - 10.0.19041.450 (WinBuild.160101.0800)
           Microsoft GDI+
[00007FF9974B0000] C:\WINDOWS\SYSTEM32\winspool.drv
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Spooler Driver
[00007FF997540000] C:\WINDOWS\SYSTEM32\msimg32.dll
           6.2.19041.450 - 10.0.19041.450 (WinBuild.160101.0800)
           GDIEXT Client DLL
[00007FF9979C0000] C:\Windows\System32\rasadhlp.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Remote Access AutoDial Helper
[00007FF998220000] C:\Windows\System32\DevDispItemProvider.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           DeviceItem inproc devquery subsystem
[00007FF9982D0000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\DLLs\select.pyd
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF9982E0000] C:\Users\OEM\AppData\Local\Programs\Python\Python38\python3.DLL
           3.8.5150.1013 - 3.8.5
           Python Core
[00007FF998590000] C:\Windows\System32\Windows.Devices.Enumeration.dll
           6.2.19041.388 - 10.0.19041.388 (WinBuild.160101.0800)
           Windows.Devices.Enumeration
[00007FF998960000] C:\WINDOWS\System32\davclnt.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Web DAV Client DLL
[00007FF998B00000] C:\WINDOWS\System32\DAVHLPR.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           DAV Helper DLL
[00007FF998B10000] C:\WINDOWS\System32\ntlanman.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft® Lan Manager
[00007FF998BE0000] C:\WINDOWS\SYSTEM32\winmm.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           MCI API DLL
[00007FF998F30000] C:\WINDOWS\System32\drprov.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft Remote Desktop Session Host Server Network Provider
[00007FF999900000] C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1_none_b555e41d4684ddec\COMCTL32.dll
           6.10.19041.1 - 6.10 (WinBuild.160101.0800)
           User Experience Controls Library
[00007FF999CB0000] C:\Windows\System32\thumbcache.dll
           6.2.19041.423 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft Thumbnail Cache
[00007FF999D20000] C:\WINDOWS\system32\dataexchange.dll
           6.2.19041.264 - 10.0.19041.264 (WinBuild.160101.0800)
           Data exchange
[00007FF999D80000] C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
           14.25.28508.3 - 14.25.28508.3 built by: vcwrkspc
           Microsoft® C Runtime Library
[00007FF99AB70000] C:\WINDOWS\SYSTEM32\TextShaping.dll
           (no module version info)
[00007FF99AEA0000] C:\WINDOWS\SYSTEM32\cscapi.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Offline Files Win32 API
[00007FF99C3A0000] C:\WINDOWS\SYSTEM32\textinputframework.dll
           6.2.19041.423 - 10.0.19041.423 (WinBuild.160101.0800)
           "TextInputFramework.DYNLINK"
[00007FF99C630000] C:\WINDOWS\SYSTEM32\iertutil.dll
           11.0.19041.423 - 11.00.19041.1 (WinBuild.160101.0800)
           Run time utility for Internet Explorer
[00007FF99CED0000] C:\WINDOWS\SYSTEM32\URLMON.DLL
           11.0.19041.117 - 11.00.19041.1 (WinBuild.160101.0800)
           OLE32 Extensions for Win32
[00007FF99DFC0000] C:\WINDOWS\System32\MMDevApi.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           MMDevice API
[00007FF99E3E0000] C:\WINDOWS\SYSTEM32\msls31.dll
           3.10.349.0 - 3.10.349.0
           Microsoft Line Services library file
[00007FF99F940000] C:\WINDOWS\System32\fwpuclnt.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           FWP/IPsec User-Mode API
[00007FF99FC30000] C:\WINDOWS\SYSTEM32\SRVCLI.DLL
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Server Service Client DLL
[00007FF99FD60000] C:\WINDOWS\SYSTEM32\mpr.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Multiple Provider Router DLL
[00007FF9A19E0000] C:\Windows\System32\PortableDeviceApi.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Portable Device API Components
[00007FF9A2E90000] C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
           6.2.19041.388 - 10.0.19041.388 (WinBuild.160101.0800)
           Microsoft Windows Codecs Library
[00007FF9A3180000] C:\WINDOWS\system32\twinapi.appcore.dll
           6.2.19041.388 - 10.0.19041.1 (WinBuild.160101.0800)
           twinapi.appcore
[00007FF9A4DE0000] C:\WINDOWS\SYSTEM32\RICHED20.DLL
           5.31.23.1231 - 5.31.23.1231
           Rich Text Edit Control, v3.1
[00007FF9A4EC0000] C:\WINDOWS\SYSTEM32\wtsapi32.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Remote Desktop Session Host Server SDK APIs
[00007FF9A50F0000] C:\WINDOWS\SYSTEM32\wintypes.dll
           6.2.19041.329 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Base Types DLL
[00007FF9A56B0000] C:\WINDOWS\system32\d3d11.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Direct3D 11 Runtime
[00007FF9A5EE0000] C:\WINDOWS\system32\dcomp.dll
           6.2.19041.388 - 10.0.19041.388 (WinBuild.160101.0800)
           Microsoft DirectComposition Library
[00007FF9A60D0000] C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
           6.2.19041.1 - 10.0.19041.1
           Microsoft Core UI Components Dll
[00007FF9A67B0000] C:\WINDOWS\SYSTEM32\CoreMessaging.dll
           6.2.19041.423 - 10.0.19041.423
           Microsoft CoreMessaging Dll
[00007FF9A69E0000] C:\WINDOWS\SYSTEM32\apphelp.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Application Compatibility Client Library
[00007FF9A6AC0000] C:\WINDOWS\system32\uxtheme.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft UxTheme Library
[00007FF9A6D10000] C:\WINDOWS\system32\propsys.dll
           7.0.19041.1 - 7.0.19041.1 (WinBuild.160101.0800)
           Microsoft Property System
[00007FF9A6E20000] C:\Windows\System32\PortableDeviceTypes.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Portable Device (Parameter) Types Component
[00007FF9A6F80000] C:\WINDOWS\SYSTEM32\DWMAPI.DLL
           6.2.19041.423 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft Desktop Window Manager API
[00007FF9A6FB0000] C:\WINDOWS\SYSTEM32\version.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Version Checking and File Installation Libraries
[00007FF9A6FF0000] C:\WINDOWS\SYSTEM32\USP10.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Uniscribe Unicode script processor
[00007FF9A7040000] C:\WINDOWS\SYSTEM32\SHFolder.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Shell Folder Service
[00007FF9A75F0000] C:\WINDOWS\SYSTEM32\windows.storage.dll
           6.2.19041.423 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft WinRT Storage API
[00007FF9A7DF0000] C:\WINDOWS\SYSTEM32\kernel.appcore.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           AppModel API Host
[00007FF9A7E60000] C:\WINDOWS\system32\dxgi.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           DirectX Graphics Infrastructure
[00007FF9A8250000] C:\WINDOWS\SYSTEM32\ntmarta.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows NT MARTA provider
[00007FF9A82C0000] C:\WINDOWS\SYSTEM32\WINSTA.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Winstation Library
[00007FF9A8600000] C:\WINDOWS\system32\rsaenh.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft Enhanced Cryptographic Provider
[00007FF9A8730000] C:\WINDOWS\System32\wkscli.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Workstation Service Client DLL
[00007FF9A8980000] C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           IP Helper API
[00007FF9A89C0000] C:\WINDOWS\SYSTEM32\NETUTILS.DLL
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Net Win32 API Helpers DLL
[00007FF9A89D0000] C:\WINDOWS\SYSTEM32\DNSAPI.dll
           6.2.19041.450 - 10.0.19041.1 (WinBuild.160101.0800)
           DNS Client API DLL
[00007FF9A8CC0000] C:\WINDOWS\system32\mswsock.dll
           6.2.19041.423 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft Windows Sockets 2.0 Service Provider
[00007FF9A8E40000] C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Base cryptographic API DLL
[00007FF9A8ED0000] C:\WINDOWS\SYSTEM32\Wldp.dll
           6.2.19041.423 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Lockdown Policy
[00007FF9A9200000] C:\WINDOWS\SYSTEM32\CRYPTSP.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Cryptographic Service Provider API
[00007FF9A9250000] C:\WINDOWS\System32\MSASN1.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           ASN.1 Runtime APIs
[00007FF9A92E0000] C:\WINDOWS\System32\DEVOBJ.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Device Information Set DLL
[00007FF9A9420000] C:\WINDOWS\SYSTEM32\Userenv.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Userenv
[00007FF9A9460000] C:\WINDOWS\SYSTEM32\profapi.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           User Profile Basic API
[00007FF9A95D0000] C:\WINDOWS\System32\WINTRUST.dll
           6.2.19041.423 - 10.0.19041.423 (WinBuild.160101.0800)
           Microsoft Trust Verification APIs
[00007FF9A9630000] C:\WINDOWS\System32\bcryptPrimitives.dll
           6.2.19041.264 - 10.0.19041.264 (WinBuild.160101.0800)
           Windows Cryptographic Primitives Library
[00007FF9A96B0000] C:\WINDOWS\System32\CRYPT32.dll
           6.2.19041.21 - 10.0.19041.1 (WinBuild.160101.0800)
           Crypto API32
[00007FF9A9810000] C:\WINDOWS\System32\KERNELBASE.dll
           6.2.19041.423 - 10.0.19041.388 (WinBuild.160101.0800)
           Windows NT BASE API Client DLL
[00007FF9A9AE0000] C:\WINDOWS\System32\win32u.dll
           6.2.19041.450 - 10.0.19041.450 (WinBuild.160101.0800)
           Win32u
[00007FF9A9B10000] C:\WINDOWS\System32\bcrypt.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Cryptographic Primitives Library
[00007FF9A9B40000] C:\WINDOWS\System32\CFGMGR32.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Configuration Manager DLL
[00007FF9A9B90000] C:\WINDOWS\System32\gdi32full.dll
           6.2.19041.388 - 10.0.19041.388 (WinBuild.160101.0800)
           GDI Client DLL
[00007FF9A9CA0000] C:\WINDOWS\System32\ucrtbase.dll
           6.2.19041.423 - 10.0.19041.423 (WinBuild.160101.0800)
           Microsoft® C Runtime Library
[00007FF9A9DA0000] C:\WINDOWS\System32\msvcp_win.dll
           6.2.19041.423 - 10.0.19041.423 (WinBuild.160101.0800)
           Microsoft® C Runtime Library
[00007FF9A9E40000] C:\WINDOWS\System32\USER32.dll
           6.2.19041.388 - 10.0.19041.1 (WinBuild.160101.0800)
           Multi-User Windows USER API Client DLL
[00007FF9A9FE0000] C:\WINDOWS\System32\ole32.dll
           6.2.19041.153 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft OLE for Windows
[00007FF9AA110000] C:\WINDOWS\System32\PSAPI.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Process Status Helper
[00007FF9AA180000] C:\WINDOWS\System32\sechost.dll
           6.2.19041.388 - 10.0.19041.1 (WinBuild.160101.0800)
           Host for SCM/SDDL/LSA Lookup APIs
[00007FF9AA220000] C:\WINDOWS\System32\Msctf.dll
           6.2.19041.388 - 10.0.19041.1 (WinBuild.160101.0800)
           MSCTF Server DLL
[00007FF9AA340000] C:\WINDOWS\System32\shlwapi.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Shell Light-weight Utility Library
[00007FF9AA3A0000] C:\WINDOWS\System32\msvcrt.dll
           7.0.19041.1 - 7.0.19041.1 (WinBuild.160101.0800)
           Windows NT CRT DLL
[00007FF9AA440000] C:\WINDOWS\System32\advapi32.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Advanced Windows 32 Base API
[00007FF9AA4F0000] C:\WINDOWS\System32\SHELL32.dll
           6.2.19041.423 - 10.0.19041.329 (WinBuild.160101.0800)
           Windows Shell Common Dll
[00007FF9AAC30000] C:\WINDOWS\System32\combase.dll
           6.2.19041.329 - 10.0.19041.1 (WinBuild.160101.0800)
           Microsoft COM for Windows
[00007FF9AAF90000] C:\WINDOWS\System32\shcore.dll
           6.2.19041.388 - 10.0.19041.1 (WinBuild.160101.0800)
           SHCORE
[00007FF9AB040000] C:\WINDOWS\System32\SETUPAPI.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Setup API
[00007FF9AB4B0000] C:\WINDOWS\System32\IMM32.DLL
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Multi-User Windows IMM32 API Client DLL
[00007FF9AB4E0000] C:\WINDOWS\System32\WS2_32.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows Socket 2.0 32-Bit DLL
[00007FF9AB5B0000] C:\WINDOWS\System32\RPCRT4.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Remote Procedure Call Runtime
[00007FF9AB6E0000] C:\WINDOWS\System32\GDI32.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           GDI Client DLL
[00007FF9AB7B0000] C:\WINDOWS\System32\NSI.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           NSI User-mode interface DLL
[00007FF9AB7C0000] C:\WINDOWS\System32\clbcatq.dll
           2001.12.10941.16384 - 2001.12.10941.16384 (WinBuild.160101.0800)
           COM+ Configuration Catalog
[00007FF9AB870000] C:\WINDOWS\System32\imagehlp.dll
           6.2.19041.1 - 10.0.19041.1 (WinBuild.160101.0800)
           Windows NT Image Helper
[00007FF9AB890000] C:\WINDOWS\System32\oleaut32.dll
           6.2.19041.388 - 10.0.19041.388 (WinBuild.160101.0800)
           OLEAUT32.DLL
[00007FF9ABB10000] C:\WINDOWS\System32\comdlg32.dll
           6.2.19041.329 - 10.0.19041.1 (WinBuild.160101.0800)
           Common Dialogs DLL
[00007FF9ABCD0000] C:\WINDOWS\System32\KERNEL32.DLL
           6.2.19041.292 - 10.0.19041.329 (WinBuild.160101.0800)
           Windows NT BASE API Client DLL
[00007FF9ABDD0000] C:\WINDOWS\SYSTEM32\ntdll.dll
           6.2.19041.423 - 10.0.19041.1 (WinBuild.160101.0800)
           NT Layer DLL
------------------------------------------------------------------------------
Active Controls hierarchy:
TSynEdit "SynEdit"
TPanel "FGPanel"
TPanel "BGPanel"
TPythonIIForm "PythonIIForm"
TJvDockVSNETTabSheetSpTBX ""
TJvDockVSNETTabPageControlSpTBX ""
TJvDockTabHostForm "TJvDockTabHostForm_CallStackWindow_VariablesWindow_0000000004FA0A10"
TJvDockVSNETPanelSpTBX "BottomDockPanel"
TPyIDEMainForm "PyIDEMainForm"
------------------------------------------------------------------------------

**Comment by vishalGoundar** [comment] 2020-09-01 22:52
Please how do I solve this problem?

**Comment by pyscripter** [comment] 2020-09-02 00:27
Please submit such reports using the Send button of the Exception form.

- Is the problem reproducible?  
- Could you provide some instructions for reproducing the error?
- Could you carry on working after say reinitializing the Python Engine.  (Run, Python Engine, Reinitialize)?
- Does it happen when you run any specific script?

Please provide any information that might help trace and resolve the issue.

**Comment by pyscripter** [comment] 2020-09-02 00:35
I just noticed that you are using the RemoteTk engine.  This engine is a special purpose one and I would recommend switching to the standard Remote engine (Run, Python Engines, Remote).  You can still run GUI scripts with the Remote Engine.

For more info see https://github.com/pyscripter/pyscripter/wiki/RemoteEngines

**Comment by pyscripter** [comment] 2021-01-06 00:49
Closing since there has been no feedback.

**Closed by pyscripter** 2021-01-06 00:49 UTC
