### ISSUE TITLE
console autohide ?

### ISSUE THREAD

**Issue by Quetzaal** [pyscripter/pyscripter#1340] opened 2024-10-29 07:59 UTC
not so long ago, i went on 5.01 (win10pro, python3.9(x64), pyscripter 5.01(x64)

and a new behaviour happened, wich was existing on my last version of y pyscripter, only because my system seem to have some particularities..

before... when i was oppening the interpreter with a shortcut, the shortcuts was the master of the window... it was never closig by it self  – no autohide  – 
but, with 5.01, this normal behaviour, is back... and it makes me some trouble... opening and closing and opnenning and closing for just a nothing... 

and no way in mode pinned, to see the window be ruled by the shortcut (open/close)...

a solution ? a new feature ? 

thank a lot for an anwser...

**Comment by pyscripter** [comment] 2024-10-29 09:39
I am afraid there is no shortcut for hiding.  The shortcut only activates  the interpreter.   I will leave this issue open to think about it.

**Comment by Quetzaal** [comment] 2024-10-31 14:27
thanks for your anwser, i'm gonna try to be clereast..

just replace the [auto-hide], by an [auto-open] feature... the auto-hide should be rules by a shortcut only (open/hide) (as it possible, but without the auto-hide)

coz, when i run a script, the auto-open feature is really pleasant... except, that it auto-hide immediately. Then i have to go click on the edge of pyscripter to re-open the interpreter window... with hundred time a day of debugging, it becomes a few grxxxx ;)))))

if you got some time in another version...

**Comment by pyscripter** [comment] 2024-10-31 14:41
Good to hear the problem is solved.  Could you please close the issue.

**Closed** 2024-11-02 12:03 UTC
