### ISSUE TITLE
Change file name, pyscripter could not refresh file name in project Explorer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#661] opened 2015-08-24 16:24 UTC
```
What steps will reproduce the problem?
1. in Win 7 with pyscripter installed, create a project and import project files
2. in Project Explorer window, right click a file, on context menu, select 
`Property`
3. in `Property` dialog, change the file name, and click 'OK' to finish.

What is the expected output? What do you see instead?

We will see that file name is not changed in Project Explorer window. 
We expect that file name changed in Project Explorer window automatically. At 
least, we should provide 'Refresh' menu to click and refresh.


What version of the product are you using? On what operating system?
Version : 2.5.3.0
OS: Win 7

Please provide any additional information below.

```

Original issue reported on code.google.com by `jcyr...@gmail.com` on 7 Jun 2012 at 6:40

**Comment by pyscripter** [comment] 2018-01-15 02:22
Duplicate of #521

**Closed by pyscripter** 2018-01-15 02:22 UTC
Labels: auto-migrated, duplicate
