### ISSUE TITLE
Scrolling after performing a CTRL+F find scrolls the "Find" dropdown, rather than the searched file

### ISSUE THREAD

**Issue by kmclaughlinphd** [pyscripter/pyscripter#874] opened 2018-04-25 19:06 UTC
To reproduce:
1. CTRL+F, type in keyword
2. press enter
3. ccroll up/down

Rather than scrolling the code, it scrolls what in the Find query box, and automatically jumps to the first result.

**Comment by pyscripter** [comment] 2018-04-26 02:56
Duplicate of #655

**Closed by pyscripter** 2018-04-26 02:56 UTC
Labels: duplicate
