### ISSUE TITLE
Scrolling inside search-field could be optional

### ISSUE THREAD

**Issue by DrCKYHC** [pyscripter/pyscripter#991] opened 2020-04-15 15:11 UTC
In older versions of PyScripter (i.e. 2.5.3 x64) the problem was bigger, but still present in current version (3.6.3-x64) using Windows 7:

If you search for something in code using CTRL+F - the search-field appears and contains text you are searching for. In older PyScripter version first match in code was automatic focused, but if you just scroll with Mouse-Wheel (to scroll the code around the match) - the scrolling within search-field occurs (i.e. switching between previous search-strings causing automatic changing of matches in code and "jumps" inside the code. So finally you get unexpected search-string and unexpected code-place.) With current PyScripter version the behaviour was improved, but still works not like expected if you press Enter after giving the text to search, i.e.:
- Place cursor somewhere in code (for example on the top)
- Press CTRL+ F
- Type the text to search for
- Press Enter to find first match (at this moment also the search Field gets focused)
- Scroll with mouse **or Cursor-keys** to scroll code around the match - the previous search strings in Search-Field are scrolled.

So in fact you was in code, like to find quickly something staying in the code-window and you get out of the code-window after the first search was performed.

Because someone might like to have possibility of scrolling within search-field, I propose following solution:
- Make the scrolling within search field optional (configurable). If disabled - scroll within code-window instead.
alternative (more complicated):
- Return focus to code-window after some text was entered and the pressed one of combinations: ["Enter", "F3", "Shift + F3", "Escape", "Cursor Up", "Cursor Down", "Mouse Wheel Scroll"]

Note: the Issue is not a duplicate of https://github.com/pyscripter/pyscripter/issues/874 (which was duplicated to https://github.com/pyscripter/pyscripter/issues/655) because you are not performing a click on source-code. The main idea is to focus result in Code-Window after first match.

**Comment by pyscripter** [comment] 2020-04-15 16:44
Duplicate of #655.

Windows 10 resolves this issue and since:
-  The vast majority of users are on Windows 10
-  Windows 7 is not supported even by Microsoft
-  It would take a significant effort to fix this for earlier versions of Windows

I cannot justify making the effort to fix it.  Sorry.

**Closed by pyscripter** 2020-04-15 16:44 UTC
Labels: duplicate

**Comment by DrCKYHC** [comment] 2020-04-15 18:10
Win7 is support by MS until end of 2020 (currently).
Ok, let wait for feedback until I will update my PC to Win 10 (expected: Q3 2020).
Trust me - it's not about environment...
