### ISSUE TITLE
Request Enhancement : Project tree should be synced with drive (file system)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#744] opened 2015-08-24 16:25 UTC
```
currently files to be added or removed manually from tree. which is ok, but 
strange. most of other dev environments worked with direct syncing on disk. few 
ide's give option. 

ideally , having 1 option in preferences is super ideal

and lucky day is, if you tell me, we already have option somewhere in 
preferences...
huge thanks for making such wonderful software
cheers.
lala
```

Original issue reported on code.google.com by `lalama...@gmail.com` on 19 Jul 2013 at 10:37

**Comment by pyscripter** [comment] 2018-12-05 10:47
Duplicate of #521

**Closed by pyscripter** 2018-12-05 10:47 UTC
Labels: auto-migrated, duplicate
