### ISSUE TITLE
2-byte characters(Japanese) Can't type inline input

### ISSUE THREAD

**Issue by DDD-G** [pyscripter/pyscripter#1347] opened 2024-11-27 06:07 UTC
2-byte characters(Japanese) Can't type inline input

Ver5.1.0 ===> No problem.
Ver5.1.1 ===> NG

I am writing this using Google Translate. Sorry.

**Comment by pyscripter** [comment] 2024-11-27 10:50
Can you provide an example input that fails?

**Comment by DDD-G** [comment] 2024-11-27 13:08
Sorry.
I was wrong about the version.

The correct information is

Ver5.0.1 ===> No problem.
Ver5.1.0 ===> NG.
Ver5.1.1 ===> NG

If you enter the text in romaji and press the space bar (convert), it will be converted into Japanese kanji or katakana.
I took a short video of the working and problematic versions.
The characters you are typing will appear outside the editor instead of inside it.


https://github.com/user-attachments/assets/96a2a771-6777-4957-b4b9-7a14bf48a84d


https://github.com/user-attachments/assets/c73ca8b1-b7ba-4474-99b4-e96b6cb5f3a4

https://github.com/user-attachments/assets/07f475b0-341e-4ee1-bf8b-33777b971a18

**Comment by pyscripter** [comment] 2024-11-27 13:23
Thank you.  This is helpful.

So the problem is the positioning of the IME Windows.   Is that right?

Normally it appears next to the Caret if there is one.  The point is that the updated PyScripter editor does not use Windows carets,

I think this https://learn.microsoft.com/en-us/answers/questions/1167835/how-can-i-move-the-ime-window-to-a-specific-positi will be the way to solve this issue.

**Comment by GGG-F** [comment] 2024-11-28 05:08
Thank you for your reply.
I had to create a new account because I forgot my password and couldn't log in.

It's not a problem with the position of the IME window.
The link you provided has simply changed the position of the IME window and has not resolved the issue.

Normally, like in the first video, the IME window does not appear and text is entered directly into the editor.
I would like it to be like Version 5.0.1, where text is entered without the IME window being displayed.

**Comment by pyscripter** [comment] 2024-11-28 06:30
Could you please download the [zip file](https://drive.google.com/file/d/1FeOCi746BX0deMzMkfZp7WIh4z_OXYmh/view?usp=sharing) and run the executable inside.

Does the IME work as in the previous versions of PyScripter?

**Comment by pyscripter** [comment] 2024-11-30 15:17
By the way could you help complete the Japanese translation at https://app.transifex.com/pyscripter/pyscripter/dashboard/?

**Comment by pyscripter** [comment] 2024-11-30 16:00
Fixed in the just released 5.1.2.  Please test and report back.

**Closed by pyscripter** 2024-11-30 16:00 UTC

**Comment by GGG-F** [comment] 2024-11-30 22:52
I immediately tried inputting Japanese using Version 5.1.2 and confirmed that the problem was resolved.
Thank you for your response and fix.

https://github.com/user-attachments/assets/0492ab2e-c0e4-41c4-8d6d-da6bce6d5701
