### ISSUE TITLE
Pyscripter not supporting Python38-venv

### ISSUE THREAD

**Issue by ManPython** [pyscripter/pyscripter#1020] opened 2020-09-17 22:00 UTC
Regarding issue, when I runing PyScripter.exe --Python38 --NEWINSTANCE then have this popup window
https://github.com/pyscripter/pyscripter/issues/1017#issuecomment-687918994
After this I have window to select Python (in case exist added). 
Looks like Pyscripter 3.6.3.0x64 not accepting situation if no exist any python in Path (I have many with venv, and I don't like in Path nothing with python). PyScripter.exe --Python36 --NEWINSTANCE working, ok. And pure PyScripter.exe  when selecting Engine as not venv just Python 3.8, then ok.
```
*** Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32. ***
*** Remote Python engine is active ***
```

Need:
+ easy way to add path without tree as vevn, just label to put ready path
+ want sugest to publish realise version on Github

**Comment by pyscripter** [comment] 2020-09-17 22:09
Just use

PyScripter.exe --Python38 --NEWINSTANCE --PYTHONDLLPATH="path-to-your-venv"

**Comment by ManPython** [comment] 2020-09-18 08:09
@pyscripter 
This not helping and crashing Pyscripter as closing and no any error or something..

**Comment by pyscripter** [comment] 2020-09-18 08:26
How did you create your virtual environments using venv or virtualenv?

**Comment by ManPython** [comment] 2020-09-18 09:43
virtualenv

**Comment by pyscripter** [comment] 2020-09-18 10:17
Virtualenv v20+ is complete rewrite and the virtual environments look very much like those created by venv.


PyScripter 3.6.3 has support for virtualenv earlier than v20.    The next version will support virtualenv v20+, but drop support for earlier virtualenv versions (changes committed).

**Comment by pyscripter** [comment] 2020-09-18 10:20
If you want I can post a pre-release version.

**Closed** 2020-09-18 10:20 UTC
Labels: fixed

**Comment by qq2898** [comment] 2021-04-21 09:14
I have the same problem, I have create a vitural environment using venv in winpython3.8 as the env path is "D:\WPy64-3890\scripts\py38", But I can't using it in pyscripter.

**Comment by pyscripter** [comment] 2021-04-21 11:02
@qq2898 
Virtualenv or venv?
Which version of PyScripter?

**Comment by qq2898** [comment] 2021-04-21 12:33
364，I have tried both virtualenv and venv



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 21, 2021 19:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pyscripter/pyscripter] Pyscripter not supporting Python38-venv (#1020)




 
@qq2898
 Virtualenv or venv?
 Which version of PyScripter?

**Comment by pyscripter** [comment] 2021-04-21 14:02
I cannot reproduce.

Created a venv
> Python38\python -m venv --system-site-packages venv38

Then 
- Run, Python Versions, Setup Python Versions
- Add
- Specified the path
- PyScripter recognized it was a venv and named it "Python 3.8 (64bit) -venv"
- Activated this version and it worked fine.
-

**Comment by qq2898** [comment] 2021-04-21 15:20
i have used winpython 3.8, and do the same as you, but still failed, may be the cause is winpython？



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 21, 2021 22:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pyscripter/pyscripter] Pyscripter not supporting Python38-venv (#1020)




 
I cannot reproduce.
 
Created a venv
 &gt; Python38\python -m venv --system-site-packages venv38 
 Then
  
Run, Python Versions, Setup Python Versions 

Add 

Specified the path 

PyScripter recognized it was a venv and named it "Python 3.8 (64bit) -venv" 

Activated this version and it worked fine.

**Comment by pyscripter** [comment] 2021-04-21 17:10
Using PyScripter v3.64 64bits
Downloaded and unziped WinPython 3.8.9

```
> cd python-3.8.9.amd64
> python -m venv c:\testvenv
```
Then as before  in PyScripter
- Run, Python Versions, Setup Python Versions
- Add
- Specified the path (path to venv38)
- PyScripter recognized it was a venv and named it "Python 3.8 (64bit) -venv"
- Activated this version and it worked fine.

**Comment by qq2898** [comment] 2021-04-21 23:06
yes, it is ok. my error is that i add the path testenv/scripts where python.exe stayed in, but not the parent dir. thanks.



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 22, 2021 01:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pyscripter/pyscripter] Pyscripter not supporting Python38-venv (#1020)




 
Using PyScripter v3.64 64bits
 Downloaded and unziped WinPython 3.8.9
 &gt; cd python-3.8.9.amd64 &gt; python -m venv c:\testvenv  
Then as before  in PyScripter
  
Run, Python Versions, Setup Python Versions 

Add 

Specified the path (path to venv38) 

PyScripter recognized it was a venv and named it "Python 3.8 (64bit) -venv" 

Activated this version and it worked fine.
