### ISSUE TITLE
What I need - list

### ISSUE THREAD

**Issue by ManPython** [pyscripter/pyscripter#909] opened 2018-10-15 11:01 UTC
In project dock 

1. Open catalog by RCM (right click mouse) 
2. Auto Refresh for Project catalog  (now I must delete Files/Project catalog and "import directory" again)
3. Save project as in dock of Projects
4. Status of autosave project (when was - hh:mm:ss) in status bar
5. Block the autohide dockswindow (hide icon) and prevent to not move mdi cards et. (I do this ancidetaly) and icons on menu (don't wan move it and the parts of separation)
6. Search - ctr+f opening input, but close must be done by "x" in belt, want close by shortcut ctr+f (this same with ctr+h as replace)
7. Sroll horizontal by mouse on mdi cards to shift to begin or end (first or last mdi card)
8. Scroll vertial on Project dock as discover that mouse is on area of this dock, I must click dock no.
9. Often is some bug and dialog window about that hange up Pyscripter coz Python engine not responding or something. Must have option to kill this dialog to back to Pyscripter without kill all IDE by ctr+shift+del as process

**Comment by pyscripter** [comment] 2018-12-05 10:56
> Search - ctr+f opening input, but close must be done by "x" in belt, want close by shortcut ctr+f (this same with ctr+h as replace)
Esc closes the Find toolbar.

> Scroll vertical on Project dock as discover that mouse is on area of this dock, I must click dock no.
This works as expected in Windows 10. See comment in #655.

> Auto Refresh for Project catalog (now I must delete Files/Project catalog and "import directory" again)
Duplicate of #521.  See comment there.


>Often is some bug and dialog window about that hange up Pyscripter coz Python engine not responding or something. Must have option to kill this dialog to back to Pyscripter without kill all IDE by ctr+shift+del as process
If you use the recommended Remote Python Engine, in recent versions of PyScripter, Run, Python Engine, Reinitialize should work quite reliably.

**Comment by pyscripter** [comment] 2018-12-05 11:01
I am closing this.  Please do not bundle multiple issues into one and create a separate issue for each request and explain the request in some more detail.

**Closed by pyscripter** 2018-12-05 11:01 UTC
