### ISSUE TITLE
Auto-complete evaluates properties instead of just checking for existence

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#759] opened 2015-08-24 16:25 UTC
```
What steps will reproduce the problem?
1. Make a class with a property that has a side-effect.
2. Assign an instance of the class to a variable.
3. Type the name of the variable, followed by a period.

What is the expected output? What do you see instead?
I expected the property to be shown in the popup auto-complete list, but to not 
be evaluated. Instead, the property gets evaluated, which means any side 
effects (an SQL query, in this case) get executed. Additionally, if there is 
any delay caused by the property being evaluated, the editor will freeze until 
the evaluation is complete.

What version of the product are you using? On what operating system?
Python Scripter version 2.5.3.0 x64, running on Windows 7 and using Python 
3.3.3.

Please provide any additional information below.


```

Original issue reported on code.google.com by `hosfor...@gmail.com` on 14 Jan 2014 at 2:44

**Comment by pyscripter** [comment] 2017-10-18 23:51
Please provide a test case.  Also please check with the latest version 3.0.  I think this was fixed.

**Comment by pyscripter** [comment] 2018-01-15 02:58
Duplicate of #422.
Fixed some time ago.

**Closed by pyscripter** 2018-01-15 02:58 UTC
Labels: auto-migrated, duplicate, fixed
