### ISSUE TITLE
EDirectoryNotFoundException on Tools, Options, Editor Options

### ISSUE THREAD

**Issue by primenumber59** [pyscripter/pyscripter#1117] opened 2021-05-13 23:13 UTC
Using the portable 32 bit version, with a file open th Tools, Options, Editor Options command generates an exception.

I note that this error does not occur after a fresh install when run with no ini files to begin with.

The log:

Exception class: EDirectoryNotFoundException
Exception message: The specified path was not found.
Exception address: 004F1696
------------------------------------------------------------------------------
PyScripter version : 4.0.0.6 x86
Python DLL : python36.dll
Python Engine : peRemote
------------------------------------------------------------------------------
Stack list, generated 14/05/2021 8:53:12 AM
[004F1691]{PyScripter.exe} System.IOUtils.TDirectory.InternalCheckDirPathParam (Line 1434, "System.IOUtils.pas" + 13)
[004F1033]{PyScripter.exe} System.IOUtils.TDirectory.CheckGetFilesParameters (Line 624, "System.IOUtils.pas" + 8)
[004F15BC]{PyScripter.exe} System.IOUtils.TDirectory.GetFiles (Line 1295, "System.IOUtils.pas" + 1)
[008F3AF7]{PyScripter.exe} dlgSynEditOptions.TSynEditOptionsDialog.Execute (Line 447, "dlgSynEditOptions.pas" + 58)
[00BC9BBA]{PyScripter.exe} dmCommands.TCommandsDataModule.actEditorOptionsExecute (Line 1276, "dmCommands.pas" + 28)
[004C67BF]{PyScripter.exe} System.Classes.TBasicAction.Execute (Line 17671, "System.Classes.pas" + 3)
[00527E6A]{PyScripter.exe} Vcl.ActnList.TCustomAction.Execute (Line 284, "Vcl.ActnList.pas" + 19)
[004C6613]{PyScripter.exe} System.Classes.TBasicActionLink.Execute (Line 17582, "System.Classes.pas" + 2)
[0082A46C]{PyScripter.exe} TB2Item.TTBCustomItem.Click (Line 1539, "TB2Item.pas" + 23)
[0085FA10]{PyScripter.exe} SpTBXItem.TSpTBXCustomItem.Click (Line 3970, "SpTBXItem.pas" + 2)
[0082A362]{PyScripter.exe} TB2Item.TTBCustomItem.ClickWndProc (Line 1488, "TB2Item.pas" + 29)
[004C7514]{PyScripter.exe} System.Classes.StdWndProc (Line 18175, "System.Classes.pas" + 8)
[005D2883]{PyScripter.exe} Vcl.Forms.TApplication.ProcessMessage (Line 11028, "Vcl.Forms.pas" + 23)
[005D28C6]{PyScripter.exe} Vcl.Forms.TApplication.HandleMessage (Line 11058, "Vcl.Forms.pas" + 1)
[005D2BFD]{PyScripter.exe} Vcl.Forms.TApplication.Run (Line 11196, "Vcl.Forms.pas" + 26)
[00C883D3]{PyScripter.exe} PyScripter.PyScripter (Line 148, "" + 16)
------------------------------------------------------------------------------
System   : Windows 7 Home Edition, Version: 6.1, Build: 1DB1, "Service Pack 1"
Processor: Intel,       Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz, 2000 MHz MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 64 bits DEP
Memory: 6121; free 2362
Display  : 1366x768 pixels, 32 bpp
------------------------------------------------------------------------------
List of loaded modules:
[00400000] C:\Users\Susan\Programs\PyScripter 4.0.0\PyScripter.exe
           4.0.0.6 - 4.0.0.6
           PyScripter Python IDE
[07770000] C:\Windows\system32\cbfsNetRdr6.dll
<10000000> 6.1.184.328 - 6, 1, 184, 328
           Network Redirector
[10000000] C:\Windows\SysWOW64\cbfsMntNtf6.dll
           6.1.184.329 - 6, 1, 184, 329
           Mount Notifier
[6BE90000] C:\Users\Susan\Python\Python36-32\DLLs\_ssl.pyd
           3.6.8150.1013 - 3.6.8
           Python Core
[6C010000] C:\Users\Susan\Python\Python36-32\python36.dll
           3.6.8150.1013 - 3.6.8
           Python Core
[6C380000] C:\Windows\system32\WMVCore.DLL
           12.0.7601.17514 - 12.0.7601.17514 (win7sp1_rtm.101119-1850)
           Windows Media Playback/Authoring DLL
[6C5F0000] C:\Windows\system32\wpdshext.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Portable Devices Shell Extension
[6C850000] C:\Users\Susan\Python\Python36-32\DLLs\unicodedata.pyd
           3.6.8150.1013 - 3.6.8
           Python Core
[6C930000] C:\Windows\system32\RICHED20.DLL
           5.31.23.1230 - 5.31.23.1230
           Rich Text Edit Control, v3.1
[6C9B0000] C:\Windows\system32\EhStorAPI.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Enhanced Storage API
[6C9E0000] C:\Windows\system32\PortableDeviceApi.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Portable Device API Components
[6CAC0000] C:\Windows\system32\XmlLite.dll
           1.3.1001.0 - 1.3.1001.0
           Microsoft XmlLite Library
[6CAF0000] C:\Windows\system32\WindowsCodecs.dll
           6.2.9200.21830 - 6.2.9200.21830 (win8_ldr.160407-0600)
           Microsoft Windows Codecs Library
[6CF40000] C:\Windows\system32\audiodev.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Portable Media Devices Shell Extension
[6CF80000] C:\Windows\system32\ntshrui.dll
           6.1.7601.17755 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Shell extensions for sharing
[6D010000] C:\Windows\system32\cscapi.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Offline Files Win32 API
[6D020000] C:\Windows\system32\wkscli.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Workstation Service Client DLL
[6D030000] C:\Windows\system32\srvcli.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Server Service Client DLL
[6D050000] C:\Windows\system32\netutils.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Net Win32 API Helpers DLL
[6D070000] C:\Windows\system32\WMASF.DLL
           12.0.7600.16385 - 12.0.7600.16385 (win7_rtm.090713-1255)
           Windows Media ASF DLL
[6D0B0000] C:\Windows\System32\davclnt.dll
           6.1.7601.23542 - 6.1.7601.23542 (win7sp1_ldr.160908-0600)
           Web DAV Client DLL
[6D0D0000] C:\Windows\System32\shdocvw.dll
           6.1.7601.23896 - 6.1.7601.23896 (win7sp1_ldr.170819-0600)
           Shell Doc Object and Control Library
[6D100000] C:\Windows\system32\EhStorShell.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Enhanced Storage Shell Extension DLL
[6D2E0000] C:\Windows\system32\netapi32.dll
           6.1.7601.17887 - 6.1.7601.17887 (win7sp1_gdr.120704-0720)
           Net Win32 API DLL
[6D4E0000] C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.23894_none_5c0be957a009922e\gdiplus.dll
           6.1.7601.23894 - 6.1.7601.23894 (win7sp1_ldr.170816-0600)
           Microsoft GDI+
[6D680000] C:\Windows\system32\msimg32.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           GDIEXT Client DLL
[6D7E0000] C:\Windows\System32\DAVHLPR.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           DAV Helper DLL
[6D840000] C:\Windows\System32\fwpuclnt.dll
           6.1.7601.18283 - 6.1.7600.16385 (win7_rtm.090713-1255)
           FWP/IPsec User-Mode API
[6D8C0000] C:\Windows\system32\rasadhlp.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Remote Access AutoDial Helper
[6D8D0000] C:\Program Files (x86)\Bonjour\mdnsNSP.dll
           3.1.0.1 - 3,1,0,1
           Bonjour Namespace Provider
[6D900000] C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live\WLIDNSP.DLL
           7.250.4311.0 - 7.250.4311.0
           Microsoft® Windows Live ID Namespace Provider
[6D930000] C:\Windows\System32\wshtcpip.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Winsock2 Helper DLL (TL/IPv4)
[6ED70000] C:\Windows\system32\PROPSYS.dll
           7.0.7601.17514 - 7.00.7600.16385 (win7_rtm.090713-1255)
           Microsoft Property System
[6F220000] C:\Windows\system32\oleacc.dll
           7.0.0.0 - 7.0.0.0 (win7sp1_gdr.110826-1504)
           Active Accessibility Core Component
[6F260000] C:\Windows\system32\winspool.drv
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Spooler Driver
[6F490000] C:\Windows\System32\wship6.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Winsock2 Helper DLL (TL/IPv6)
[6F4A0000] C:\Windows\System32\mswsock.dll
           6.1.7601.23451 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft Windows Sockets 2.0 Service Provider
[6F4E0000] C:\Windows\system32\rsaenh.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft Enhanced Cryptographic Provider
[6F520000] C:\Windows\system32\CRYPTSP.dll
           6.1.7601.24382 - 6.1.7601.24382 (win7sp1_ldr.190210-0600)
           Cryptographic Service Provider API
[6F540000] C:\Windows\system32\ntmarta.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows NT MARTA provider
[6F570000] C:\Windows\system32\api-ms-win-crt-conio-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6F760000] C:\Windows\system32\DNSAPI.dll
           6.1.7601.17570 - 6.1.7600.16385 (win7_rtm.090713-1255)
           DNS Client API DLL
[6F8E0000] C:\Windows\system32\dwmapi.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft Desktop Window Manager API
[6F900000] C:\Windows\system32\uxtheme.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft UxTheme Library
[6F980000] C:\Windows\system32\api-ms-win-crt-utility-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6F990000] C:\Windows\system32\api-ms-win-crt-math-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6F9A0000] C:\Windows\system32\api-ms-win-crt-environment-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6F9B0000] C:\Windows\system32\api-ms-win-crt-time-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6F9C0000] C:\Windows\system32\api-ms-win-crt-filesystem-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6F9D0000] C:\Windows\system32\api-ms-win-crt-locale-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6F9E0000] C:\Windows\system32\api-ms-win-crt-convert-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6F9F0000] C:\Windows\system32\api-ms-win-crt-stdio-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6FA00000] C:\Windows\system32\api-ms-win-crt-string-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6FA10000] C:\Windows\system32\api-ms-win-crt-heap-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6FA20000] C:\Windows\system32\api-ms-win-core-file-l1-2-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6FA30000] C:\Windows\system32\api-ms-win-core-processthreads-l1-1-1.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6FA40000] C:\Windows\system32\api-ms-win-core-localization-l1-2-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6FA50000] C:\Windows\system32\api-ms-win-core-file-l2-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6FA60000] C:\Windows\system32\api-ms-win-core-timezone-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6FA70000] C:\Windows\system32\ucrtbase.DLL
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           Microsoft® C Runtime Library
[6FB60000] C:\Windows\system32\api-ms-win-crt-runtime-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[6FC00000] C:\Windows\system32\winmm.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           MCI API DLL
[6FC40000] C:\Windows\system32\mpr.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Multiple Provider Router DLL
[70DE0000] C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_41e855142bd5705d\COMCTL32.dll
           6.10.7601.18837 - 6.10 (win7_rtm.090713-1255)
           User Experience Controls Library
[71250000] C:\Windows\system32\WINNSI.DLL
           6.1.7601.23889 - 6.1.7601.23889 (win7sp1_ldr.170810-1615)
           Network Store Information RPC interface
[71260000] C:\Windows\system32\Iphlpapi.DLL
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           IP Helper API
[71280000] C:\Windows\system32\version.DLL
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Version Checking and File Installation Libraries
[72E70000] C:\Windows\system32\api-ms-win-core-synch-l1-2-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[72E80000] C:\Windows\system32\WINSTA.dll
           6.1.7601.18540 - 6.1.7601.18540 (win7sp1_gdr.140716-1508)
           Winstation Library
[72EB0000] C:\Windows\system32\wtsapi32.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Windows Remote Desktop Session Host Server SDK APIs
[72F70000] C:\Windows\System32\ntlanman.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft® Lan Manager
[72F90000] C:\Windows\System32\drprov.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Microsoft Remote Desktop Session Host Server Network Provider
[72FA0000] C:\Windows\system32\IconCodecService.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Converts a PNG part of the icon to a legacy bmp icon
[72FB0000] C:\Windows\system32\slc.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Software Licensing Client Dll
[72FC0000] C:\Windows\system32\olepro32.dll
           6.1.7601.17514 - 6.1.7601.17514
[74280000] C:\Windows\system32\apphelp.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Application Compatibility Client Library
[744E0000] C:\Users\Susan\Python\Python36-32\DLLs\_socket.pyd
           3.6.8150.1013 - 3.6.8
           Python Core
[74500000] C:\Users\Susan\Python\Python36-32\VCRUNTIME140.dll
           14.0.24234.1 - 14.00.24234.1 built by: VCTOOLSD14ULDR
           Microsoft® C Runtime Library
[74520000] C:\Users\Susan\Python\Python36-32\DLLs\select.pyd
           3.6.8150.1013 - 3.6.8
           Python Core
[74530000] C:\Users\Susan\Python\Python36-32\python3.dll
           3.6.8150.1013 - 3.6.8
           Python Core
[75320000] C:\Windows\system32\api-ms-win-crt-process-l1-1-0.dll
           10.0.10586.1171 - 10.0.10586.1171 (th2_release_sec.170901-1821)
           ApiSet Stub DLL
[75330000] C:\Windows\system32\SHFolder.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Shell Folder Service
[75520000] C:\Windows\syswow64\CRYPTBASE.dll
           6.1.7601.24384 - 6.1.7601.24384 (win7sp1_ldr_escrow.190220-1800)
           Base cryptographic API DLL
[75530000] C:\Windows\syswow64\SspiCli.dll
           6.1.7601.24384 - 6.1.7601.24384 (win7sp1_ldr_escrow.190220-1800)
           Security Support Provider Interface
[75590000] C:\Windows\syswow64\RPCRT4.dll
           6.1.7601.24384 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Remote Procedure Call Runtime
[75680000] C:\Windows\syswow64\PSAPI.DLL
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Process Status Helper
[75690000] C:\Windows\syswow64\WLDAP32.dll
           6.1.7601.23889 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Win32 LDAP API DLL
[756E0000] C:\Windows\syswow64\api-ms-win-downlevel-normaliz-l1-1-0.dll
           6.2.9200.16492 - 6.2.9200.16492 (win8_gdr_oobssr.130113-0015)
           ApiSet Stub DLL
[756F0000] C:\Windows\syswow64\api-ms-win-downlevel-shlwapi-l1-1-0.dll
           6.2.9200.16492 - 6.2.9200.16492 (win8_gdr_oobssr.130113-0015)
           ApiSet Stub DLL
[75700000] C:\Windows\syswow64\WININET.dll
           11.0.9600.18858 - 11.00.9600.18860 (winblue_ltsb.171113-1555)
           Internet Extensions for Win32
[759B0000] C:\Windows\syswow64\SETUPAPI.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Setup API
[75B50000] C:\Windows\syswow64\MSCTF.dll
           6.1.7601.23915 - 6.1.7600.16385 (win7_rtm.090713-1255)
           MSCTF Server DLL
[75C20000] C:\Windows\syswow64\MSASN1.dll
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           ASN.1 Runtime APIs
[75C30000] C:\Windows\syswow64\CRYPT32.dll
           6.1.7601.24382 - 6.1.7601.24382 (win7sp1_ldr.190210-0600)
           Crypto API32
[75D90000] C:\Windows\syswow64\profapi.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           User Profile Basic API
[75DA0000] C:\Windows\syswow64\shlwapi.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Shell Light-weight Utility Library
[75E00000] C:\Windows\syswow64\USP10.dll
           1.626.7601.23894 - 1.0626.7601.23894 (win7sp1_ldr.170816-0600)
           Uniscribe Unicode script processor
[75EA0000] C:\Windows\syswow64\DEVOBJ.dll
           6.1.7601.17621 - 6.1.7601.17621 (win7sp1_gdr.110523-2108)
           Device Information Set DLL
[75EC0000] C:\Windows\syswow64\api-ms-win-downlevel-version-l1-1-0.dll
           6.2.9200.16492 - 6.2.9200.16492 (win8_gdr_oobssr.130113-0015)
           ApiSet Stub DLL
[75ED0000] C:\Windows\syswow64\URLMON.DLL
           11.0.9600.18858 - 11.00.9600.18858 (winblue_ltsb.171107-0923)
           OLE32 Extensions for Win32
[76080000] C:\Windows\syswow64\USERENV.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Userenv
[760A0000] C:\Windows\syswow64\normaliz.DLL
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Unicode Normalization DLL
[760B0000] C:\Windows\syswow64\KERNELBASE.dll
           6.1.7601.24384 - 6.1.7601.18015 (win7sp1_gdr.121129-1432)
           Windows NT BASE API Client DLL
[76100000] C:\Windows\syswow64\CFGMGR32.dll
           6.1.7601.17621 - 6.1.7601.17621 (win7sp1_gdr.110523-2108)
           Configuration Manager DLL
[76130000] C:\Windows\syswow64\WINTRUST.dll
           6.1.7601.24382 - 6.1.7601.24382 (win7sp1_ldr.190210-0600)
           Microsoft Trust Verification APIs
[76160000] C:\Windows\syswow64\msvcrt.dll
           7.0.7601.17744 - 7.0.7601.17744 (win7sp1_gdr.111215-1535)
           Windows NT CRT DLL
[76210000] C:\Windows\syswow64\SHELL32.dll
           6.1.7601.23893 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Windows Shell Common Dll
[76E60000] C:\Windows\syswow64\GDI32.dll
           6.1.7601.23914 - 6.1.7601.23914 (win7sp1_ldr.170908-0600)
           GDI Client DLL
[76EF0000] C:\Windows\syswow64\api-ms-win-downlevel-advapi32-l1-1-0.dll
           6.2.9200.16492 - 6.2.9200.16492 (win8_gdr_oobssr.130113-0015)
           ApiSet Stub DLL
[76F00000] C:\Windows\syswow64\iertutil.dll
           11.0.9600.18858 - 11.00.9600.18858 (winblue_ltsb.171107-0923)
           Run time utility for Internet Explorer
[77140000] C:\Windows\syswow64\NSI.dll
           6.1.7601.23889 - 6.1.7601.23889 (win7sp1_ldr.170810-1615)
           NSI User-mode interface DLL
[77150000] C:\Windows\syswow64\LPK.dll
           6.1.7601.23930 - 6.1.7601.23930 (win7sp1_ldr.171011-1526)
           Language Pack
[77160000] C:\Windows\syswow64\ADVAPI32.dll
           6.1.7601.24384 - 6.1.7601.24384 (win7sp1_ldr_escrow.190220-1800)
           Advanced Windows 32 Base API
[77210000] C:\Windows\syswow64\api-ms-win-downlevel-user32-l1-1-0.dll
           6.2.9200.16492 - 6.2.9200.16492 (win8_gdr_oobssr.130113-0015)
           ApiSet Stub DLL
[77220000] C:\Windows\syswow64\WS2_32.dll
           6.1.7601.23451 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Windows Socket 2.0 32-Bit DLL
[77260000] C:\Windows\syswow64\api-ms-win-downlevel-ole32-l1-1-0.dll
           6.2.9200.16492 - 6.2.9200.16492 (win8_gdr_oobssr.130113-0015)
           ApiSet Stub DLL
[77270000] C:\Windows\syswow64\kernel32.dll
           6.1.7601.24384 - 6.1.7601.18015 (win7sp1_gdr.121129-1432)
           Windows NT BASE API Client DLL
[77380000] C:\Windows\syswow64\comdlg32.dll
           6.1.7601.17514 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Common Dialogs DLL
[77400000] C:\Windows\syswow64\CLBCatQ.DLL
           2001.12.8530.16385 - 2001.12.8530.16385 (win7_rtm.090713-1255)
           COM+ Configuration Catalog
[77490000] C:\Windows\SysWOW64\sechost.dll
           6.1.7600.16385 - 6.1.7600.16385 (win7_rtm.090713-1255)
           Host for SCM/SDDL/LSA Lookup APIs
[774B0000] C:\Windows\system32\IMM32.DLL
           6.1.7601.17514 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Multi-User Windows IMM32 API Client DLL
[77510000] C:\Windows\syswow64\oleaut32.dll
           6.1.7601.23775 - 6.1.7601.23775
[775B0000] C:\Windows\syswow64\USER32.dll
           6.1.7601.23594 - 6.1.7601.17514 (win7sp1_rtm.101119-1850)
           Multi-User Windows USER API Client DLL
[776B0000] C:\Windows\syswow64\ole32.dll
           6.1.7601.23889 - 6.1.7601.23889 (win7sp1_ldr.170810-1615)
           Microsoft OLE for Windows
[77C80000] C:\Windows\SysWOW64\ntdll.dll
           6.1.7601.24384 - 6.1.7600.16385 (win7_rtm.090713-1255)
           NT Layer DLL
------------------------------------------------------------------------------
Active Controls hierarchy:
TSynEdit "SynEdit"
TSpTBXTabSheet "tbshSource"
TSpTBXTabControl "ViewsTabControl"
TPanel "BGPanel"
TEditorForm "EditorForm"
TSpTBXTabSheet "SpTBXTabSheet1"
TSpTBXTabControl "TabControl1"
TPanel "BGPanel"
TPyIDEMainForm "PyIDEMainForm"
------------------------------------------------------------------------------

**Comment by pyscripter** [comment] 2021-05-14 00:11
I cannot reproduce it here.
I see that the program runs from the C:\Users\Susan\Programs\PyScripter 4.0.0\. Do you have a directory C:\Users\Susan\Programs\Highlighters ?

You should extract all contents of PyScripter-4.0.0-x86.zip in the directory of your choice.

**Comment by pyscripter** [comment] 2021-05-14 01:08
Closing on the basis of the comments https://groups.google.com/d/msgid/pyscripter/6165eebe-32df-4702-a410-c44c62ce85f8n%40googlegroups.com

**Closed by pyscripter** 2021-05-14 01:08 UTC
