### ISSUE TITLE
Feature Request: Change-Projects -- Change loaded files

### ISSUE THREAD

**Issue by phedlund113** [pyscripter/pyscripter#1006] opened 2020-06-18 16:49 UTC
When saving the project, save the files open in the ide at the time. So when you open a project, you will also open the files open when the project was last used.

Remember what files are open in the project.

I don't know if this is possible but its a request.

**Comment by pyscripter** [comment] 2021-04-14 00:44
Would you close open files and then open the files open when the project was saved or you would keep existing files open and then open any additional files from the project?

**Comment by pyscripter** [comment] 2021-04-17 23:31
Duplicate of #942

**Closed by pyscripter** 2021-04-17 23:31 UTC
Labels: duplicate, enhancement
