### ISSUE TITLE
pyscripter interpriter hangs with code completion

### ISSUE THREAD

**Issue by tapdo** [pyscripter/pyscripter#964] opened 2019-08-12 09:32 UTC
pyscripter interpriter often hangs or petit Freeze trying code completion whcih have many candidate variable to completion, for example wx object, numpy...

Example, pyscripter interpriter freezing to try complete after "rt." 
![image](https://user-images.githubusercontent.com/5471106/62856272-66f5ad00-bd2f-11e9-808b-ed9d92032c3b.png)

Running pyscripter 3.6.1.0 x64, with python 3.6 (using Remote wx engine)

**Comment by pyscripter** [comment] 2019-08-16 00:11
Do you try to autocomplete after running the script?

Could you please provide the script as text (not as a picture) to facilitate the testing?

**Comment by pyscripter** [comment] 2019-09-27 21:10
Cannot reproduce

![tempsnip](https://user-images.githubusercontent.com/1311616/65802430-4faa3c00-e184-11e9-9e2e-b39b785796b6.png)
I am getting code completion on rt (Textctrl).

**Comment by pyscripter** [comment] 2019-09-27 21:15
And by the way you do not need the wx engine to run/debug wx scripts.  See this [wiki page](https://github.com/pyscripter/pyscripter/wiki/RemoteEngines) for details

**Comment by pyscripter** [comment] 2019-12-05 03:41
I am closing this since there is no further feedback and the issue cannot be reproduced..

**Closed by pyscripter** 2019-12-05 03:41 UTC
Labels: cannot reproduce
