### ISSUE TITLE
Jupyter notebook in PyScripter 3.4.2.0 x64

### ISSUE THREAD

**Issue by sancho-s** [pyscripter/pyscripter#1184] opened 2022-11-16 12:59 UTC
I am using PyScripter-4.2.1-x64 portable (PS1), with a Python from Portable Python 3.7.1 x64, which came with a bundled PyScripter 3.4.2.0 x64 (PS2).
I mean to get PS1 or PS2 to read Jupyter notebooks.
This is what I did and what I get in PS1 (for PS2 I posted [a separate question](https://github.com/pyscripter/pyscripter/issues/1185)):

PS1:
1. Install jupyter via pip.
2. Close and reopen PS1.
3. Open an existing and working .ipynb file (created via anaconda Jupyter notebook)
4. Tools -> Source code views -> Web Preview
This prints the following in the Output Window
>     Command line: C:\Users\USER1\DOCUME~1\APPLS_~1\DEVELO~1\PORTAB~1.1X6\App\Python\Scripts\Jupyter-notebook.exe --no-browser --NotebookApp.token=""
>     Working directory: C:\Users\USER1\DOCUME~1\python
>     Timeout: 0 ms
and the following in the Browser window, where I expected to see/edit the notebook (my translation from Spanish)
> The page cannot be accessed
>     Make sure the web address http://localhost:8888 is correct. 
>     ...

**How can I solve this?**

**Comment by pyscripter** [comment] 2022-11-16 15:19
Duplicate of #1185

**Closed by pyscripter** 2022-11-16 15:19 UTC
Labels: duplicate
