### ISSUE TITLE
frequently hangs

### ISSUE THREAD

**Issue by jodyhey** [pyscripter/pyscripter#910] opened 2018-10-15 13:25 UTC
pyscripter hangs pretty frequently  - just hangs and will not respond.  It does this one to three times a day   (I develop or review code for about 4 hours a day)
Running x64 version,  with  python 3.6.5 anaconda distribution.  remote engine 
using a lot of numpy, scipy and matplotlib.

**Comment by pyscripter** [comment] 2018-10-15 16:11
Does this happen while running/debugging scripts?   What happens when it hangs.   Do you get an error report?  Do you have to kill it from the Task Manager?

One thing to try when this happens.  Go to the Task Manager and in the Details tab find a process named "Python".  Right-click it and select "End task".   Does PyScripter recover after that? 

Any other info about might cause this, and help trace and resolve the issue would be helpful.

**Comment by jodyhey** [comment] 2018-10-16 18:29
Sorry I was not more clear.   What happens in each of these instances is that Pyscripter is waiting for something.  The pointer is replaced by a small spinning thing.   I've tried waiting for awhile  (e.g. 1/2 hour), but to no avail.  I kill it just by clicking on the 'x' in the upper right corner.

**Comment by pyscripter** [comment] 2018-10-16 18:53
One thing to try when this happens. Go to the Task Manager and in the Details tab find a process named "Python". Right-click it and select "End task". Does PyScripter recover after that?

**Comment by jodyhey** [comment] 2018-10-17 13:49
The most common circumstance, is when I return to pyscripter in the morning  and it will not respond.  It also hangs this way sometimes when I have been debugging/editing. 

So upon returning to my desktop this morning I returned to pyscripter to find it would not respond and had a the spinning circle.  
There are three python.exe tasks listed in details.  One with 11 gigs listed under Memory.  The other two had much more modest memory values.

When I ended this task in task manager,  pyscripter remained open and is still hung (though now the screen is opaque and it says "not responding at the top". 

I then ended the second python.exe task, with no change in pyscripter.   
I then ended the third python.exe,  again with no change in pyscripter. 

hope that helps. 

![taskmanager](https://user-images.githubusercontent.com/3298692/47090338-ba22d000-d1f0-11e8-839f-f1e3a7c4439d.png)

**Comment by jodyhey** [comment] 2018-10-17 14:34
oh and I'm running pyscripter 3.4.2.0 x64

**Comment by pyscripter** [comment] 2018-10-17 14:46
Thank you for the information.  However, it is kind of hard to figure what where to search for the problem.  If I understood what you said, this does not appear to be related to running or debugging scripts.  You also stated that you are using the remote engine and I guess you are reinitializing before each run (which is the default).

So if you can provide any more clues about the possible cause do come forward.  For instance,

- Is it related to the use of pandas, geopandas? (https://groups.google.com/forum/#!topic/pyscripter/GFEmGHe-OEM)
- Is it related to code completion?
- Does it depend on the nature of scripts you are working?
- Could it be related to the FIle Explorer and network drive mappings?

**Comment by jodyhey** [comment] 2018-10-17 15:57
not pandas (I use it but not a lot) and definitely not geopandas
code completion page screenshot attached 
I'm not using remote files much,  python.exe and scripts are local
Not seeing any dependency on the kind of scripts.    Mostly they are number crunching and some plotting. 

One thing - I have fallen into frequently using the interpreter window while debugging,  where I enter statements into the interpreter window for evaluation,  when pyscripter is stopped at a break point in the code.  And then I'll resume the debugging session.  
I'm not sure how/why this works,  but its a nice feature if indeed it is intended to be so.  

hope some of that helps

**Comment by jodyhey** [comment] 2018-10-17 15:57
here is code completion page
![image](https://user-images.githubusercontent.com/3298692/47099696-d67c3800-d203-11e8-8b55-e5482f3c7e20.png)

**Comment by dunha** [comment] 2018-10-25 08:00
I have also notice this issue.
Using 3.4.2 32 bit on Windows 10 Python 2.7.13
Usually occurs while Pyscripter is in the background. Hasn't happened to me while in use so far.
It even occurs if no script has been run or edited after some time in the background
It will terminate with the close button but not close as intended. Haven't had to use task manager.
I thought it might be because of  so many scripts open, but occured with just one open
I don't have mapped network drives but I do have UNC shortcuts in Explorer. Pretty much all scripts are on the local drive.

**Comment by pyscripter** [comment] 2018-10-25 11:40
I wonder whether it relates to this: https://stackoverflow.com/questions/20142166/explain-errors-from-getkeystate-getcursorpos/20142404?sgp=2#20142404 .


> I found the following situations which might likely trigger these errors:
> -Login after user switching in Windows
> -Login from password protected screensavers
> -VNC / Remote Desktop Services
> 

I will try to add a workaround in the next version.

**Comment by pyscripter** [comment] 2018-10-25 23:36
Added potential fix in version control.

**Comment by dunha** [comment] 2018-10-26 01:47
Thanks. I hadn't noticed this in previous versions

**Comment by marshall-ucsd** [comment] 2018-11-29 18:56
Still a serious issue in 3.5.1. No clear trigger. Just now I started typing "de" to create a new class method (at the top of an existing class), and it's locked up. Left it a little to see if it comes back, but ultimately had to force-stop it.

It was open for hours before the hang, off-and-on editing. 

Win 7 Pro, Python 3.6.7 x64 - Using virtual environment (which might be important?)

**Comment by philnagel** [comment] 2018-12-12 03:05
I am also experiencing this on 3.5.1.

**Comment by pyscripter** [comment] 2019-01-03 01:16
The above update has been reported to resolve this issue.

Here are updated links to the 32 bit and 64 bit executables (3.5.2 preview)
- [x64 (64bits)](https://drive.google.com/file/d/1MBIj7YeJAXtAj2yEk5-22GJJraQ5DDVT/view?usp=sharing)
- [x86 (32bits)](https://drive.google.com/file/d/1Bk4OlZ789Xqu6wPjwJEpGCM4Vmp_xtYj/view?usp=sharing)

Could you please test with regard to this issue.

A lot of features have been added, so please report any other issues that you may find.  This will help make the next release more robust.  Here is the main changes:

History:   v 3.5.2
- New Features
            - Much faster Remote Engine using asynchronous Windows named pipes if pywin32 is available.
            - IDE option to force the use of sockets for connection to the Python server now defaults to False
            - Enhancements to the SSH Engine - now compatible with PuTTY
            - Execute system commands in the interpreter with !. Supports parameter substitution.
            - Clickable status panels with Python version and engine type
            - Text drag & drop between PyScripter and other applications (#554)
            - Triple-click selects line and Quadraple-click selects all
            - Double-click drag selects whole words - triple-click drag selects whole lines
            - Consistent syntax color themes accross supported languages (#855)
- Issues addressed
            - #904, #922, #927, 928, #929, #936

**Comment by jodyhey** [comment] 2019-01-04 15:07
thanks!.   I swapped it in.
    On Wednesday, January 2, 2019, 8:17:00 PM EST, pyscripter <notifications@github.com> wrote:  
 
 
The above update has been reported to resolve this issue.

Here are updated links to the 32 bit and 64 bit executables (3.5.2 preview)
   
   - x64 (64bits)
   - x86 (32bits)

Could you please test with regard to this issue.

A lot of features have been added, so please report any other issues that you may find. This will help make the next release more robust. Here is the main changes:

History: v 3.5.2
   
   - New Features   
- Much faster Remote Engine using asynchronous Windows named pipes if pywin32 is available.   
- IDE option to force the use of sockets for connection to the Python server now defaults to False   
- Enhancements to the SSH Engine - now compatible with PuTTY   
- Execute system commands in the interpreter with !. Supports parameter substitution.   
- Clickable status panels with Python version and engine type   
- Text drag & drop between PyScripter and other applications (#554)   
- Triple-click selects line and Quadraple-click selects all   
- Double-click drag selects whole words - triple-click drag selects whole lines   
- Consistent syntax color themes accross supported languages (#855)
   - Issues addressed   
- #904, #922, #927, 928, #929, #936

**Comment by UnderJollyRoger** [comment] 2019-01-04 17:14
I am having the same hanging issue after updating to v3.5.1 (32bit)/Python 2.7.13. I haven't tried the update with Python 3x because I'm using the arcpy module, which only runs on Python 2.7. When I run a script it produces the expected results with no errors, but in the Interpreter it hangs on the first print statement and never completes. When I hit the close button I get this message:
![image](https://user-images.githubusercontent.com/32503258/50700960-a594ed80-1011-11e9-91b0-f7f167d77f33.png)

I've been following this thread and have used the updated 32 bit executable. No change.

**Comment by pyscripter** [comment] 2019-01-04 17:35
@UnderJollyRoger This is a rather different issue from the one discussed in this thread.

The problem in your case is that the script you are running somehow breaks the communication with PyScripter. 

-  Does this occur with any script (say print("HI")?
-  If not can you post a simple sample script that reproduces the issues.

**Comment by UnderJollyRoger** [comment] 2019-01-04 20:09
Thanks for the quick response.

- No, it does not occur with `print("hi")`
- I can't seem to reproduce the issue? I've tried a few other scripts with and without the arcpy module and they all completed. It seems to only be one particular script. Funny, because it never had an issue before the Pyscripter update.

**Comment by pyscripter** [comment] 2019-01-07 13:30
@jodyhey Any feedback?

**Comment by pyscripter** [comment] 2019-01-10 22:55
@jodyhey Could you please turn the new IDE option Tools, Options, IDE Options, File Explorer, Background Processing to False and report whether it makes things better?

**Comment by dunha** [comment] 2019-01-14 08:20
I haven't had problems since I set the explorer background processing as suggested (couple of days) - using 3.5.1 32 bit
Also not having issues with swapping remote engines any more (issue [#880](https://github.com/pyscripter/pyscripter/issues/880)) but don't think that is related
Haven't tried 3.5.2 as I can't find a portable version
Tried using WingIDE in the meantime but didn't like it as much as PyScripter

**Comment by duyduc27** [comment] 2019-02-14 13:12
I got the same problem. At first, I used 3.5 x64 version then uninstall and reinstall 3.6.0.0 x64 version instead. I didn't add much libraries, just clicking and coding but the IDE was frequently hung many times. Then I have to close the program by using Task Manager. My OS system is Window 7 Ultimate SP 1.

**Comment by pyscripter** [comment] 2019-02-14 17:11
Which version of python?  Are you be any chance using files with non-ascii file paths?

**Comment by duyduc27** [comment] 2019-02-15 13:17
> Which version of python? Are you be any chance using files with non-ascii file paths?

My python version is 3.7.0 . I didn't use files with non-ascii but you have the point, I usually switch "keyboard tool" to use my Vietnamese characters. May it caused that problem because I was careless and typed Vietnamese character in a chance?
By the way, I tried to use pyscripter 3.5 version instead. Then it keep saying that could not to the remote Python engine server.

**Comment by Zoinkity** [comment] 2019-03-04 18:40
Same issue.  I'm also doing everything possible wrong:
1) non-ascii file paths all over the place
2) All files are utf-8 and most include non-ascii characters
3) some paths use symbolic links and/or junctions
4) fallback non-unicode language is shift JIS
5) Language bar active and typically switch between four different languages

When the hang occurs language bar's language indicator will disappear, like when you start a program and no language is specified.  Killing python does nothing.
I think tooltips are what's setting it off.  When all features generating handy tooltips are disabled the only condition that causes a hang is a language switch.  The delay is about right too.

In low available memory situations the remote debugger will also disconnect and may or may not reconnect if you keep kicking it.  It may cause a hang, but that's probably unrelated to the overall issue.  That can be recovered by killing any python processes, though you're really better off just restarting the IDE in general after closing whatever (dozen) things are eating that ram.

**Comment by dDoid** [comment] 2019-06-23 09:28
I too had this problem.
Pyscripter v3.6.0.0 x64, remote engine
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32

When running some scripts using the run button, the script would hang.
The only way of getting out of this was to renitialise the python engine.

The same script would run using the internal engine.

In the uk we use a console page of 850, active code page of 1252.
I seem to have problems involving characters where the encodings are diffferent i.e. 
in code page 850, 20(dec), 156, 170, ie pilcrow, pound, negation characters

In a short interactive session the session hangs in a similar way.
This occurs when attempts are made to display a line containing a syntax error with one of these
characters are in it, even if only in the comment.


*** Remote Interpreter Reinitialized  ***
>>> print "a"  #
a
>>> print "a"" #
  File "<interactive input>", line 1
    print "a"" #
               ^
SyntaxError: EOL while scanning string literal
>>> print "a"" #b
  File "<interactive input>", line 1
    print "a"" #b
                ^
SyntaxError: EOL while scanning string literal
>>> print "a"" #£

The session just hangs after the £.
In interactive mode, the expected message appears.


I now move on the an example script encoded in 1252.

#!coding:1252
import sys
p = "a"
up = p.decode("1252")
print "{} : {:02x}".format(p, ord(p))
print up

This worked fine.
But changing the p = "a" to p = "£"    (pound sign, chr(156))
would cause it to hang.

I then reasoned that it could be that the python interpreter was actually putting out a message but
was getting stuck in rpcy, so I added a sys.stdin.flush() after each print.
It worked!

Hope this helps.

**Comment by pyscripter** [comment] 2019-06-25 13:29
@dDoid 
I have reproduced the problem and working on it.  That was helpful.

**Comment by pyscripter** [comment] 2019-07-09 23:57
@dDoid  The error you have reported has been fixed.  The fix will be available in the next version.  So PyScripter will no longer hang in the cases you mention.

Please note that the default encoding in python 2.x is ascii.   The coding comment affects only the encoding of the source code and not the python encoding used to convert sting literals to unicode. So the correct way to print £ is the second statement.

```
#!coding:1252
print "£"
print u"£"
```

**Comment by dDoid** [comment] 2019-07-11 13:18
Thank you for your efforts.

I was aware of the use of the coding statement. I encoded the file in 1252 as I know this is what pyscripter expects.

I agree that in an ideal world print u"£" would be the preferred option.
But when you want to redirect / pipe the output, sys.stdout.encoding is set to None, python uses defaultencoding - ansi - 7bit. Any attempt to print the unicode codepoint of a character in the bottom half of the cp850 will then blow up.

**Comment by pyscripter** [comment] 2019-12-03 00:19
I am closing this since this is based on a few versions old PyScripter.  Please open a new issue if you have similar problems with PyScripter 3.6.2 or later.

**Closed by pyscripter** 2019-12-03 00:19 UTC

**Comment by Llamero** [comment] 2020-10-14 23:32
I am having a similar issue with PyScripter 3.6.4.0 x64 running on Windows 10 x64.  The window spontaneously hangs for about 5-20 seconds about every 10 minutes or so.  I have not noticed it hanging while I am running code, but it does hang while typing code.  It seems to hang most often when changing from another window back to PyScripter.

**Comment by dougbrowning** [comment] 2022-05-18 21:36
Came here to say me too!  3.6.4.0 x86 on WIndows 10.  Python 2.7.16

It seems related to the script being on a network drive.  I have to copy the .py local and it helps.  It sometimes sits right away and does nothing.  Not really hanging just not doing anything.  Other times it will do the first print then just sit.

Today now it started just not showing the prints but actually running in the background.  I eventually ended it and then found out it had worked but was just sitting.  Also today when it does run it will do one print, then sit, then all of sudden all the prints come at one and the script is done.

I have to use the old Python for ArcMap so I am stuck.  thanks

**Comment by miky1007** [comment] 2023-03-02 07:44
I'm using "Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:43:28) [MSC v.1934 32 bit (Intel)] on win32." and Pyscripter 4.2.5.0 x86 (which I appreciate!). Unfortunately it gets stuck frequently, but only during debugging and when I try to write something , in the interpreter (when execution stops at some breakpoint). 
My OS is Windows 10 version 21H2. THe only way to get back to work is terminating the job in task manager.
It's pretty annoying, and I don't want to switch to another IDE, because, i repeat I like Pyscripter very much!
