### ISSUE TITLE
Pyscriptor and I can't run the command idk why its not totally green I'm new noob here

### ISSUE THREAD

**Issue by NOOR-BYTE-DOTCOM** [pyscripter/pyscripter#1312] opened 2024-07-05 15:37 UTC
![172019
![IMG_20240705_210703](https://github.com/pyscripter/pyscripter/assets/174818700/bed2697e-df6a-46a8-9b35-056d02f0d082)

3776727845558178639354180](https://github.com/pyscripter/pyscripter/assets/174818700/bb11ca9e-1a55-4660-8596-f1453be6760c)

**Comment by pyscripter** [comment] 2024-07-05 18:52
Duplicate of #1311

**Closed by pyscripter** 2024-07-05 18:52 UTC
Labels: duplicate
