### ISSUE TITLE
Increase font size in debugger windows

### ISSUE THREAD

**Issue by cssyphus** [pyscripter/pyscripter#871] opened 2018-04-18 17:27 UTC
I love the ability to drag the debugger windows onto a second monitor (love it!), but sure would appreciate the ability to increase (change? set?) the font size in the debugger windows.

Can this be changed right now somewhere in the Windows registry or via a settings file? Otherwise, will await enhancement in later version, if RFE is approved.

**Comment by pyscripter** [comment] 2018-04-18 21:53
Is it the debugger windows only that you want to be able to change the font?  These windows have the same font size as the rest of the IDE.
Or you want to be able to change the font of all the UI?

**Comment by gibberishbc** [comment] 2018-04-18 21:59
It is possible to change the font in the Editor windows via:
Tools ==> Options ==> Editor Options --> Display (tab) --> Editor font

In the same [Display] tab, it is also possible to change the font size of the Gutter (e.g. line numbers)

However, the Debugger windows (Call Stack, Variables, Watches, Breakpoints, Output, Messages, Python Interpreter) do not seem to have a way to change the font size. (And it's pretty small... perhaps 7 point?)

Please correct me if I missed seeing where this is possible...

**Comment by pyscripter** [comment] 2018-04-18 22:45
Of course you can customize the editor fonts and a few other.
But the Debugger windows fonts should be the same size as all other IDE windows (File explorer, Code Explorer, Editor tabs etc.), which in windows 10 is 9 pt.  What is the screen you are using?  What is the text magnification factor?  Can you post a screen shot here?

**Comment by gibberishbc** [comment] 2018-04-20 16:28
Apologies for delay responding, we are working overtime to complete a build. Looking at this again, I see I was mistaken that the Debugger window font size is smaller than the Editor windows. I had dragged the Debugger window over to a second monitor, which happened to be my laptop, which has a 1/3 smaller screen at nearly the same resolution, making the font size appear 1/3 smaller.

Still, this situation show why -- at least in my own case -- it would be useful to increase the size of the Debugger window fonts separately from the Editor windows.

**Comment by philnagel** [comment] 2018-12-14 15:21
>I had dragged the Debugger window over to a second monitor, which happened to be my laptop, which has a 1/3 smaller screen at nearly the same resolution, making the font size appear 1/3 smaller.

Though this is an old comment, I just wanted to point out that you should be able to take care of this issue simply by adjusting the scaling on your laptop screen. It seems to have a higher DPI than your other display, so scaling will allow you to make them look similar, while retaining its higher resolution.

**Comment by pyscripter** [comment] 2019-12-03 00:22
Do you get the same issue with PyScripter 3.6.2?  Which version of Windows are you using?

**Comment by pyscripter** [comment] 2023-08-07 00:04
#1209 which was fixed is a duplicate of this one.  In the next release you will be able to adjust the font size of UI content including debugger windows.

**Closed by pyscripter** 2023-08-07 00:04 UTC
